### ISSUE TITLE
Feature request "port"

### ISSUE THREAD

**Issue by gitxmax** [MD5HashBrowns/zoomeye-search#2]
Thanks for your work, this is the only properly working zoomeye script, I could find on github.
Small feature request, is to add the port string to the results, so, if possible, the result for the search will look like:
ip:port
xx.xxx.xx.x:xx

Thanks again!

**Comment by adcar** [comment]
You can now specify `--port` to include the port in results :sunglasses:

E.g.:
```
$ ./zoomeye.py -p 1 "IIS"  --port 
203.160.176.142:9030
203.81.110.91:9030
203.99.232.61:9030
203.115.31.75:9030
203.112.212.126:9030
203.154.236.12:9030
203.239.190.23:9030
203.142.136.52:9030
203.236.215.250:9030
203.44.6.229:9030
111.93.9.77:100
111.93.139.140:100
111.93.11.106:100
111.93.27.203:100
111.93.20.249:100
111.93.14.243:100
111.93.0.146:100
111.68.51.133:100
192.198.241.150:32400
12.18.174.234:7479
```
I only added this to the host platform as I'm assuming web is always port 80 (and the ZoomEye API doesn't give any port info).
