### ISSUE TITLE
Save hostname or domain instead of IP

### ISSUE THREAD

**Issue by syrius01** [MD5HashBrowns/zoomeye-search#3]
Hi!

I'm a big fan of this tool, I would like to thank you for sharing this with the community :) I was wondering if it would be possible to add an option for saving the 'domains' or 'hostnames' instead of IPs in results.txt ?

Thank you for your time

**Comment by adcar** [comment]
Would you want this for just the web platform? (e.g., `./zoomeye.py --platform web`)?
The reason I'm asking is because ZoomEye doesn't provide hostnames for most hosts in `host` mode in their API. They do provide domains in their web mode, however.

**Comment by adcar** [comment]
Added a `--domain` option for web platform that accomplishes this.
