### ISSUE TITLE
--domain option

### ISSUE THREAD

**Issue by syrius01** [MD5HashBrowns/zoomeye-search#4]
Hi!

Thanks for adding the domain option so quickly :) I tried it with the following syntax:

python3 zoomeye.py -p 10 --email my@email --password my-password -s --domain "wordpress"

all the results i got was only IPs, no domains

Thank you for your time

**Comment by adcar** [comment]
You'll need to change the platform type to `web`, like so:
```
python3 zoomeye.py -p 10 --email my@email --password my-password -s --domain --platform web "wordpress"
```

**Comment by syrius01** [comment]
awesome, it works, thx for the great support !

**Comment by adcar** [comment]
Np :smiley:
