### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by JohnOfCode** [MD5HashBrowns/zoomeye-search#5]
Hello, I'm trying to use the script but it is not working anymore. could you take a look and see if you can fix it?

**Comment by adcar** [comment]
Works for me. Have you installed the Python `requests` package?
If installing `requests` doesn't fix it could you post the full output from your terminal please?

Also, make sure your using python 3.x and not python 2.x (`python --version`)

**Comment by gitxmax** [comment]
Works here fine, perhaps, the api limit has been exhausted?

**Comment by adcar** [comment]
Closed due to inactivity.
