### ISSUE TITLE
Stopped working - SyntaxError

### ISSUE THREAD

**Issue by gitxmax** [MD5HashBrowns/zoomeye-search#7]
Have been running the script for months, with no issues, now getting an error.
Upgraded the script to the latest, but didn't help.
Thanks.
 
 File "zoomeye.py", line 112
    print(BLUE + "[*] Parsing page: " + str(page), end='\r')
                                                      ^
SyntaxError: invalid syntax

**Comment by gitxmax** [comment]
fixed by running the script as ./
running as python zoomeye.py fails

**Comment by adcar** [comment]
@gitxmax your machine likely has python2 as the default so running with `python` will run the script with python 2. `./` works because the script detects the right version to use. Using `python3` would probably work for you as well (depending on the distro / OS you're using)
