### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by gitxmax** [MD5HashBrowns/zoomeye-search#8]
There's an issue, I'm experiencing with the script.
Sometimes it works fine and I get the search results properly saved in a  file, but, many times, the file is empty, despite the message, that X ip's are saved to the file.

**Comment by adcar** [comment]
I'm not sure why this would happen. Will this bug occur with the exact same command that previously worked? Or does it only occur when you try certain search terms or arguments?

**Comment by gitxmax** [comment]
seems like the problem is related to -s option and saving the results into a file
when I was running it from the command line, without the -s option, it would print the results into stdout, most of the times. But, once in a while, would spit out some errors.

I'm now back to the older version of the script and using > instead of the -s, works every time.
The only issue with using > to save the results, is that the script appends "^[[K^[[0m" to the beginning of the every result's line, which I clean up with "sed -i 's/.*0m//'"

**Comment by adcar** [comment]
Are you using the multithreaded option `-m`? If so I think this might be a cause and I can look into that. 

Also, I think I'll be removing the `--quiet` option for shell redirection and require the `--save / -s` option as it's pretty redundant.

**Comment by adcar** [comment]
Need more info. Closing this since it's two years old now, feel free to reopen if you're still having this issue.
